language: cpp

sudo: false

# Do not build branches of the form "pr/*". By prefixing pull requests coming
# from branches inside the repository with pr/, this avoids building both the
# branch push _and_ the pull request.
branches:
  except: /pr\/.*/

matrix:
  include:
    - env: PYGMO_BUILD_TYPE="Debug"
      os: osx
      osx_image: xcode10.3
script:
    - mkdir build
    - cd build
    - ../tools/travis_osx.sh

notifications:
  email: false
